name: '🤖 提交助手 | Submit Agent'
description: '提交助手设定 | Submit an agent setting'
title: '[Agent] 你的助名称 | Replace it with your agent name'
labels: ['🤖 Agent PR']
body:
  - type: textarea
    attributes:
      label: 'systemRole'
      description: |
        助手的 `Prompt` 提示词, 如果需要使用进阶配置，请参考 README 提 PR 流程
        Agent `prompt`, If you need to use advanced configurations, please refer to the README and follow the PR process
    validations:
      required: true
  - type: input
    attributes:
      label: 'identifier'
      description: |
        助手的标识符需要是唯一的，比如 `web-development`
        Agent identifier should be unique and written in English, Ex: `web-development`
    validations:
      required: true
  - type: input
    attributes:
      label: 'avatar'
      description: |
        助手的头像可以是表情符号 `🤯` 或者图片链接
        Agent avatar should be emoji or logo url
    validations:
      required: true
  - type: input
    attributes:
      label: 'title'
      description: |
        助手的名称
        Agent title, will auto generate i18n in workflow
    validations:
      required: true
  - type: input
    attributes:
      label: 'description'
      description: |
        助手的一句话简短介绍
        Agent short description, will auto generate i18n in workflow
    validations:
      required: true
  - type: input
    attributes:
      label: 'tags'
      description: |
        助手的分类 Tags 使用 `,` 进行分割
        Agent tags split by `,`
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 'locale'
      options:
        - en-US
        - zh-CN
      description: |
        以上提交的语言分类，默认为英文 `en-US`
        You can set locale if you use other i18n language, default is `en-US`
    validations:
      required: true
